---
- name: Install MariaDB server
  become: yes
  package:
    name: mariadb-server
    state: present

- name: Configure MariaDB for OpenStack
  become: yes
  copy:
    dest: /etc/mysql/conf.d/openstack.cnf
    content: |
      [mysqld]
      bind-address = 0.0.0.0
      default-storage-engine = innodb
      innodb_file_per_table = on
      max_connections = 4096
      collation-server = utf8_general_ci
      character-set-server = utf8


- name: Enable and start MariaDB service
  become: yes
  service:
    name: mysql
    state: started
    enabled: yes

